### ISSUE TITLE
Generate documentation using Stardoc

### ISSUE THREAD

**Issue by ar3s3ru** [masmovil/bazel-rules#34]
I've noticed that the rules documentation, currently in the [README](./README.md), are out-of-date from the actual rules implementations. Example: #32 introduced new fields in `helm_release`, which are not reflected in the README.

An idea to remove this inconsistency could be to use [Stardoc](https://github.com/bazelbuild/stardoc) to automatically generate documentation.

[rules_docker](https://github.com/bazelbuild/rules_docker) for example uses it for the `container_*` targets. More info here: https://github.com/bazelbuild/rules_docker/pull/1890

**Comment by pmoncadaisla** [comment]
Thanks @ar3s3ru , you are right, documentation is not up to date, and your solution is pretty atractive! We will look into this.
We have a new release of rules comming, which are backwards compatible but they have been rewritten from zero. Now they are written in Go rathen than bash. They solve some race conditions issues and they are friendlier with remote build execution systems.

**Comment by danigar** [comment]
We are generating the rules docs with stardoc in new v1.0.0.
