### ISSUE TITLE
Prepare for new release based in Go

### ISSUE THREAD

**Issue by pmoncadaisla** [masmovil/bazel-rules#38]
We have a new release of rules coming, which are backward compatible but they have been rewritten from zero. 

Now they are written in Go rather than bash. They solve some race conditions issues and they are friendlier with remote build execution systems.

**Comment by chickenandpork** [comment]
@pmoncadaisla any update on this?  I've got a few PRs awaiting the current 3 to be accepted, wondering where the new version is at.
