### ISSUE TITLE
Helm chart output archive is not reproducible

### ISSUE THREAD

**Issue by christian-roggia** [masmovil/bazel-rules#55]
The current setup invokes the `tar` command instead of leveraging on the existing `pkg_tar` [rules](https://github.com/bazelbuild/rules_pkg). This results in the output archive (.tgz) changing after each new instance invocation, triggering cache invalidation and rebuilds of targets.

**Comment by danigar** [comment]
Hi @christian-roggia! Thanks for pointing this out. The actual rules are just a wrapper around helm commands (with some extra func). Seems like `helm package` is not producing reproducible outputs. Here you can find the explanation why https://github.com/helm/helm/issues/3612#issuecomment-525340295 and this is the proper fix https://github.com/helm/helm/pull/10178 (not merged yet). 
To avoid depending on the fix to be merged, we are implementing a new version leveraging on the existing `pkg_tar` rules as per your suggestion.

**Comment by danigar** [comment]
Already implemented with new v1.0.0 using `pkg rules`.
