### ISSUE TITLE
Repo Maintenance Inquiry

### ISSUE THREAD

**Issue by iDiogenes** [masmovil/bazel-rules#68]
Hello,

First, I'd like to thank you for creating and maintaining helm rules for bazel. I've been using it to manage helm charts in my repo and even extended it in my own repo to perform[ helm linting](https://github.com/masmovil/bazel-rules/compare/master...CloudSoda:bazel-rules:jtrout/task-4899).

I've noticed that there hasn't been much recent activity, and there are some open issues and potential enhancements that could benefit the community. Moreover, with the introduction of bzlmod this repo will eventually need to be updated to support it. Can you provide any insights into the current state of this repository? Is there a plan to upgrade to support bzlmod?

Cheers.

**Comment by danigar** [comment]
Hi @iDiogenes!

Thank you very much for your interest. I'm currently working on making this repo `bzlmod` compatible. I'm also taking advance of this to introduce some changes to the rules, adding support for helm linting and other major improvements.

You can follow the advances in this [branch](feat/bzlmod).

**Comment by danigar** [comment]
We have deployed a new version of the rules addressing many new features.
